version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node-backend
    ports:
      - '3001:3000'
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_pass@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  mongo-data:
